---
name: cmpsc-203-spring-2021-lab08
break: true
indent: 4
---

# --> check the technical writing
conduct.md:
    ConfirmFileExists

assessment.md:
    ConfirmFileExists

# --> check the technical writing
report.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 14 --exact
    CountMarkdownTags --tag "code_block" --count 1
    CountMarkdownTags --tag "list" --count 6 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the number of commits beyond a threshold
CountCommits --count 3
